connect 'jdbc:derby:/home/yard/projects/databases/simpleDB;create=true';
CREATE SCHEMA alice;
CREATE SCHEMA bob;
CREATE SCHEMA dba;
CREATE SCHEMA HOMEDB;
CREATE SCHEMA SECURITY;

CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.database.sqlAuthorization', 'true');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY ('derby.user.alice', '111');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY ('derby.user.bob', '123');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY ('derby.user.dba', '12345');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY ('derby.database.fullAccessUsers', 'dba');

CREATE TABLE SECURITY.WEBUSERS(ID INTEGER, NAME VARCHAR(50), FULL_NAME VARCHAR(200), WEBROLE INTEGER, PRIMARY KEY (ID));
CREATE TABLE SECURITY.WEBROLES(ID INTEGER, NAME VARCHAR(100), DBROLE VARCHAR(20), PRIMARY KEY (ID));

CREATE TABLE HOMEDB.HUB_TYPES(ID INTEGER, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE HOMEDB.HUB_ITEMS(ID INTEGER, CODE VARCHAR(10), PRIMARY KEY (ID));
CREATE TABLE HOMEDB.LNK_TYPES_ITEMS(ID INTEGER, HUB_TYPE INTEGER, HUB_ITEM INTEGER, PRIMARY KEY (ID));
CREATE TABLE HOMEDB.SAT_BOOKS(ID INTEGER, HUB_ITEM INTEGER, AUTHOR VARCHAR(50), NAME VARCHAR(200), SERIES VARCHAR(40), GENRE VARCHAR(40), PUBLISHER VARCHAR(40), PBYEAR INTEGER, NOTE VARCHAR(256), PRIMARY KEY (ID));

disconnect;




