connect 'jdbc:derby:/home/yard/projects/databases/simpleDB';
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.database.sqlAuthorization', 'true');
CREATE ROLE dbreader;
CREATE ROLE dbwriter;
CREATE ROLE dbadmin;

GRANT SELECT ON TABLE SECURITY.WEBUSERS TO dbreader;
GRANT SELECT ON TABLE SECURITY.WEBROLES TO dbreader;
GRANT SELECT ON TABLE SECURITY.WEBUSERS TO dbwriter;
GRANT SELECT ON TABLE SECURITY.WEBROLES TO dbwriter;
GRANT ALL PRIVILEGES ON TABLE SECURITY.WEBUSERS TO dbadmin;
GRANT ALL PRIVILEGES ON TABLE SECURITY.WEBROLES TO dbadmin;

GRANT SELECT ON TABLE HOMEDB.HUB_TYPES TO dbreader;
GRANT SELECT ON TABLE HOMEDB.HUB_ITEMS TO dbreader;
GRANT SELECT ON TABLE HOMEDB.LNK_TYPES_ITEMS TO dbreader;
GRANT SELECT ON TABLE HOMEDB.SAT_BOOKS TO dbreader;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HOMEDB.HUB_TYPES TO dbwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HOMEDB.HUB_ITEMS TO dbwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HOMEDB.LNK_TYPES_ITEMS TO dbwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HOMEDB.SAT_BOOKS TO dbwriter;

GRANT ALL PRIVILEGES ON TABLE HOMEDB.HUB_TYPES TO dbadmin;
GRANT ALL PRIVILEGES ON TABLE HOMEDB.HUB_ITEMS TO dbadmin;
GRANT ALL PRIVILEGES ON TABLE HOMEDB.LNK_TYPES_ITEMS TO dbadmin;
GRANT ALL PRIVILEGES ON TABLE HOMEDB.SAT_BOOKS TO dbadmin;

GRANT dbreader TO alice, bob;
GRANT dbwriter TO bob;
GRANT dbadmin TO dba;

CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY ('derby.connection.requireAuthentication', 'true');
disconnect;